### ISSUE TITLE
Question - TopCoat still Adobe Supported?

### ISSUE THREAD

**Issue by nravulapalli** [topcoat/topcoat#494]
Is Adobe still supporting topcoat development? Last Blog post is in November. I don't see any mention of topcoat on http://html.adobe.com/opensource/

Please advise.

Thanks

**Comment by iaef** [comment]
I would love to know the actual status of this... @GarthDB any comments?
I believe that there must still be some things left in the back, since it is at 0.8.0, which means there was something planned for 0.9.0 and 1.0.0 but I do not find a clear roadmap, as for some more people to come in and put some effort to acquire such completeness status. Or maybe 0.8.0 is completeness status. But what is pending here is dev documentation effort, as to move this thing further on.

**Comment by GarthDB** [comment]
@iaef Adobe is not supporting Topcoat.  @kristoferjoseph and I want to work on it, but life is busy and we're working hard to carve out time.

**Comment by Cryrivers** [comment]
@GarthDB is Adobe still using TopCoat to build Brackets? or has it ever done this? Since TopCoat has not been updated for more than 1 year, can I still trust it and use it if I want to build a new web app now?

**Comment by GarthDB** [comment]
@Cryrivers you can trust it as far as it is working for you. It is css, it isn't going to break anything.

It wasn't actually used in brackets, it was used in some other adobe products that are no longer in production. We are looking to resume work on Topcoat, but it will be on our own time, Adobe is not committed to it now.

**Comment by mscreenie** [comment]
Would be great to see this project get some fresh air, I really like the concept and currently can't find anything to replace this from a ui perspective.

**Comment by GarthDB** [comment]
@mscreenie I would love some help if you want to make any contributions.

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe.
